import styles from './Identity.module.css'

const PILLARS = [
  {
    id: '01',
    icon: '◈',
    title: 'AI-Powered Signal Energy',
    body: 'CLAWSIGNAL doesn\'t react to the market — it anticipates it. Every signal is generated by pattern recognition layers trained on market microstructure.',
    metric: 'LATENCY',
    metricValue: '0.001ms',
  },
  {
    id: '02',
    icon: '◎',
    title: 'Market Predator Mentality',
    body: 'While retail chases candles, CLAW identifies the exact apex — the moment of maximum volatility before the move. Precision over speed.',
    metric: 'WIN RATE',
    metricValue: '—',
  },
  {
    id: '03',
    icon: '◉',
    title: 'Data-Driven Dominance',
    body: 'No narrative. No sentiment. Pure signal. Volume profiles, order flow imbalances, and momentum divergence collapsed into a single entry point.',
    metric: 'SIGNALS/DAY',
    metricValue: '∞',
  },
  {
    id: '04',
    icon: '◐',
    title: 'Institutional Trading Vibe',
    body: 'The aesthetic is Nasdaq. The discipline is quant. CLAWSIGNAL bridges the gap between meme culture and institutional grade analysis.',
    metric: 'STYLE',
    metricValue: 'QUANT',
  },
]

export default function Identity() {
  return (
    <section id="identity" className={styles.section}>
      <div className={styles.bgGrid} />

      <div className={styles.container}>
        <div className={styles.sectionHeader}>
          <span className={styles.sectionTag}>◈ CORE IDENTITY</span>
          <h2 className={styles.sectionTitle}>
            Built different.<br />
            <span className={styles.titleAccent}>Designed to dominate.</span>
          </h2>
          <p className={styles.sectionSub}>
            Four foundational pillars that define what CLAWSIGNAL is — and isn't.
          </p>
        </div>

        <div className={styles.pillars}>
          {PILLARS.map((p) => (
            <div key={p.id} className={styles.pillar}>
              <div className={styles.pillarTop}>
                <span className={styles.pillarId}>{p.id}</span>
                <span className={styles.pillarIcon}>{p.icon}</span>
              </div>
              <h3 className={styles.pillarTitle}>{p.title}</h3>
              <p className={styles.pillarBody}>{p.body}</p>
              <div className={styles.pillarMetric}>
                <span className={styles.metricLabel}>{p.metric}</span>
                <span className={styles.metricValue}>{p.metricValue}</span>
              </div>
            </div>
          ))}
        </div>

        {/* Positioning statement */}
        <div className={styles.positioning}>
          <div className={styles.posLeft}>
            <span className={styles.posTag}>POSITIONING</span>
            <p className={styles.posStatement}>
              "The precision strike of DeFi. While others spray bullets, CLAWSIGNAL fires once — at the right moment, with maximum force."
            </p>
          </div>
          <div className={styles.posDivider} />
          <div className={styles.posRight}>
            <div className={styles.posGrid}>
              {[
                ['Category', 'Memecoin'],
                ['Personality', 'Algorithmic'],
                ['Tone', 'Intelligent · Precise'],
                ['Audience', 'Financial Traders'],
                ['Differentiator', 'Signal, not noise'],
              ].map(([k, v]) => (
                <div key={k} className={styles.posRow}>
                  <span className={styles.posKey}>{k}</span>
                  <span className={styles.posVal}>{v}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
